### ISSUE TITLE
Changing from the currently playing podcast in a playlist to another and then back to the original causes it to restart

### ISSUE THREAD

**Issue by snoo21** [Podcast-Republic/PodcastRepublic-iOS#8]
https://user-images.githubusercontent.com/72040270/219518745-3bf4a022-fade-48ed-8489-a27506a0c28e.MOV

**Comment by gemiren** [comment]
Thanks for the bug report. Will look into it and fix it asap

**Comment by gemiren** [comment]
Fixed in the latest beta version. You can join the beta program on App Store to get the latest beta installed. Thanks.

**Comment by snoo21** [comment]
Hi Gemiren, 
Thanks for promptly addressing this bug, however, I don’t think that the solution is working. I am using the beta version (and the newest update from TestFlight) and I’m still experiencing the bug. I’ve tried to attach another screen recording but I’m uncertain if GitHub is letting me do that in this comment 

>

**Comment by gemiren** [comment]
Sorry to hear the fix didn't work. Can you go to app Settings > About page to double check the version number? The latest beta version should be 23.2.3.217. Thanks.

**Comment by snoo21** [comment]
Yes I can confirm it is this version number


________________________________

**Comment by gemiren** [comment]
All right. Will look into it again. Thanks.

**Comment by gemiren** [comment]
By the way, can you send the app log? Please reproduce this bug first, then please go to app Settings > About page to use Report a bug button to send the log file. Thanks.

**Comment by snoo21** [comment]
I am attempting it now but upon pressing "Report a bug" the app immediately crashes (I do have the Debug log option above enabled). Any further advice?

**Comment by gemiren** [comment]
Got the crash report from TestFlight. I'm looking into it now. Thanks.

**Comment by gemiren** [comment]
Should be fixed in today's beta update now. Please let me know if you still can reproduce this bug. Thanks.

**Comment by snoo21** [comment]
Looks to be good now, thank you!

**Comment by gemiren** [comment]
Awesome. Thanks for confirming the fix.
